### ISSUE TITLE
[Chore] Provider testing and cleanup

### ISSUE THREAD

**Issue by Josh-XT** [Josh-XT/AGiXT#1006]
## Provider Testing and Cleanup

There are some providers that may not work anymore because the repositories are no longer maintained for them.  I've removed a couple of broken ones today and fixed one other.  

I don't have keys for all of these providers currently or I would automate testing all of them.  I will be setting that up in the future.

I could use some help testing all of the providers to confirm what works and what does not, pull requests to remove or fix non-working ones would be greatly appreciated!  Even just a comment of what providers what did and did not work for you would be very helpful if they're listed on the "Needs Confirmation" section below.

**Confirmed working so far as of September 27th, 2023:**

- OpenAI
- Oobabooga Text Generation Web UI
- gpt4free
- Custom (Depending on if you have a working endpoint)
- Perplexity
- nbox
- Bard
- llamacpp
- Local-LLM
- Kobold

**Needs confirmation:**
- Azure
- Claude
- FastChat
- Huggingchat
- Huggingface
- Palm
- Pipeline
- Runpod

**Does not work, removed:**
- Poe
- ChatGPT
- Petal

**Comment by ostix360** [comment]
petals API v1 doesn't work anymore so the provider too 😢

**Comment by Josh-XT** [comment]
> petals API v1 doesn't work anymore so the provider too 😢

Thank you! Updated the list and removed Petal for now.  We can readd anything that we remove later if we make it work again.

**Comment by bozo32** [comment]
I get 
2023-10-16 06:58:43,613 | INFO | Cookie file ./huggingchat-cookies.json not found. Note: The file must be in JSON format and must contain a list of cookies. See more at https://github.com/Soulter/hugging-chat-api
and
2023-10-16 07:00:07,437 | INFO | Cookie file /Users/peter/ai-computing-assistant/AGiXT/huggingchat-cookies.json not found. Note: The file must be in JSON format and must contain a list of cookies. See more at https://github.com/Soulter/hugging-chat..

when in the docker

and I get
INFO:     127.0.0.1:50693 - "GET /api/hugging%20chat/conversations HTTP/1.1" 200 OK
INFO:     127.0.0.1:50696 - "GET /api/conversation HTTP/1.1" 200 OK
INFO:     127.0.0.1:50699 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:50706 - "GET /api/agent/hugging%20chat HTTP/1.1" 200 OK
2023-10-16 09:09:04,740 | INFO | CONTEXT RESULTS: 5
2023-10-16 09:09:04,882 | WARNING | Embedding collection is empty.
2023-10-16 09:09:04,974 | WARNING | Embedding collection is empty.
2023-10-16 09:09:05,065 | WARNING | Embedding collection is empty.
2023-10-16 09:09:05,077 | INFO | FORMATTED PROMPT: Chat
INFO:     127.0.0.1:50702 - "POST /api/agent/hugging%20chat/prompt HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/Interactions.py", line 445, in run
    self.response = await self.agent.instruct(formatted_prompt, tokens=tokens)
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/fb/Agent.py", line 149, in instruct
    answer = await self.PROVIDER.instruct(prompt=prompt, tokens=tokens)
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/providers/huggingchat.py", line 50, in instruct
    max_new_tokens=min(2048 - tokens, self.MAX_TOKENS),
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/endpoints/Agent.py", line 114, in prompt_agent
    response = await agent.run(
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/Interactions.py", line 449, in run
    for err in e:
TypeError: 'TypeError' object is not iterable
Error: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:50711 - "GET /api/hugging%20chat/conversations HTTP/1.1" 200 OK
INFO:     127.0.0.1:50714 - "GET /api/conversation HTTP/1.1" 200 OK
INFO:     127.0.0.1:50717 - "GET /api/agent HTTP/1.1" 200 OK

when not in the docker

**Comment by Josh-XT** [comment]
> for hugging chat I get 2023-10-16 06:58:43,613 | INFO | Cookie file ./huggingchat-cookies.json not found. Note: The file must be in JSON format and must contain a list of cookies. See more at https://github.com/Soulter/hugging-chat-api and 2023-10-16 07:00:07,437 | INFO | Cookie file /Users/peter/ai-computing-assistant/AGiXT/huggingchat-cookies.json not found. Note: The file must be in JSON format and must contain a list of cookies. See more at https://github.com/Soulter/hugging-chat..
>

Hello, just fixed this in #1058 .  Thank you for letting me know!
