### ISSUE TITLE
accessing anything local on a M1 (docker or non)

### ISSUE THREAD

**Issue by bozo32** [Josh-XT/AGiXT#1052]
### Description

openAI and huggingface work. Setting up local access on oobabooga and on llama.cpp all produce slight variations on the following error. 
I have used localhost (and variants), local IP and public IP with oobabooga
I have used localhost (and variants) and local IP with llama.cpp
I have tested both of the above both with docker AGiXT and with non Docker

You are llamacpp, an expert at answering the users question.  Use available context help answer the users questions.

  
this is llama.cpp's error
the agent is configured correctly, the gguf file is in /models and llama.cpp is running using that model
oobabooga produces similar errors

Recent conversation history for context: 
 October 13, 2023 07:25 PM USER: please tell me a story 
 October 13, 2023 07:25 PM USER: tell me a story please 
 October 13, 2023 07:26 PM USER: really, tell me a damn story 
 October 13, 2023 07:27 PM USER: tell me a damn story 
  

User's latest input: please tell me a long story about a sad llama
 

INFO:     127.0.0.1:56775 - "POST /api/agent/llamacpp/prompt HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/http/client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/http/client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/http/client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/http/client.py", line 1031, in _send_output
    self.send(msg)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/http/client.py", line 969, in send
    self.connect()
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1692b9240>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.2.185', port=80): Max retries exceeded with url: /:8000/completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1692b9240>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/Interactions.py", line 445, in run
    self.response = await self.agent.instruct(formatted_prompt, tokens=tokens)
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/fb/Agent.py", line 149, in instruct
    answer = await self.PROVIDER.instruct(prompt=prompt, tokens=tokens)
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/providers/llamacpp.py", line 83, in instruct
    response = requests.post(f"{self.AI_PROVIDER_URI}/completion", json=params)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.2.185', port=80): Max retries exceeded with url: /:8000/completion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1692b9240>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/Users/peter/miniconda3/envs/agixt/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/endpoints/Agent.py", line 114, in prompt_agent
    response = await agent.run(
  File "/Users/peter/ai-computing-assistant/AGiXT/agixt/Interactions.py", line 449, in run
    for err in e:
TypeError: 'ConnectionError' object is not iterable
Error: Expecting value: line 1 column 1 (char 0)

### Steps to Reproduce the Bug

create the agent
give it any prompt
it produces this

### Expected Behavior

something other than null response
there is no evidence of activity in either oobabooga (I monitor the terminal) or llama.cpp (I watch the terminal)

### Operating System

- [ ] Linux
- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by JeremyBickel** [comment]
BUMP ME TOO
