### ISSUE TITLE
Problem with git clone and script run / option 6 run agixt without docker

### ISSUE THREAD

**Issue by WillTryToDoItRight** [Josh-XT/AGiXT#1077]
### Description

gitclone
./AGiXT.sh
option 6

following:
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: python-debian 0.1.43ubuntu1 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-debian or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Already up to date.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Running local install...
Already up to date.
Running AGiXT Core...
Please wait...
Starting AGiXT...
INFO:     Uvicorn running on http://0.0.0.0:7437 (Press CTRL+C to quit)
INFO:     Started parent process [32099]
Process SpawnProcess-10:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-8:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-9:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Process SpawnProcess-6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/g3n3r3luser/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/app.py", line 6, in <module>
    from endpoints.Agent import app as agent_endpoints
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/endpoints/Agent.py", line 4, in <module>
    from Interactions import Interactions
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Interactions.py", line 9, in <module>
    from readers.website import WebsiteReader
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/home/g3n3r3luser/Programming/AGiXT/agixt/Memories.py", line 6, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'
Running Streamlit Web UI...
./AGiXT.sh: line 379: streamlit: command not found

### Steps to Reproduce the Bug

see above

### Expected Behavior

AGiXT starts normally

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Running without docker is not supported on any operating system. It is an option for me and anyone who has the same development environment as me or the docker container.
