### ISSUE TITLE
M4A Audio in base64 being passed to AGiXT not working and sees it as WAV

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1090]
### Description

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/3f3a53f1-651c-40cd-8ddb-1d3c9b09e0b7)
When I passed the Command through the Typescript SDK it doesn't M4A even though it is being passed in the command as shown in the screenshot above, since they have different codec its just not working.

```
agixt_1  | <class 'list'>
agixt_1  | whisper_init_from_file_no_state: loading model from '/agixt/models/whispercpp/ggml-base.en.bin'
agixt_1  | whisper_model_load: loading model
agixt_1  | whisper_model_load: n_vocab       = 51864
agixt_1  | whisper_model_load: n_audio_ctx   = 1500
agixt_1  | whisper_model_load: n_audio_state = 512
agixt_1  | whisper_model_load: n_audio_head  = 8
agixt_1  | whisper_model_load: n_audio_layer = 6
agixt_1  | whisper_model_load: n_text_ctx    = 448
agixt_1  | whisper_model_load: n_text_state  = 512
agixt_1  | whisper_model_load: n_text_head   = 8
agixt_1  | whisper_model_load: n_text_layer  = 6
agixt_1  | whisper_model_load: n_mels        = 80
agixt_1  | whisper_model_load: ftype         = 1
agixt_1  | whisper_model_load: qntvr         = 0
agixt_1  | whisper_model_load: type          = 2
agixt_1  | whisper_model_load: mem required  =  310.00 MB (+    6.00 MB per decoder)
agixt_1  | whisper_model_load: adding 1607 extra tokens
agixt_1  | whisper_model_load: model ctx     =  140.66 MB
agixt_1  | whisper_model_load: model size    =  140.54 MB
agixt_1  | whisper_init_state: kv self size  =    5.25 MB
agixt_1  | whisper_init_state: kv cross size =   17.58 MB
agixt_1  | WAV file '/agixt/WORKSPACE/bf7ce7de42504c3f93510e13e43594be.wav' must be 16-bit
agixt_1  | INFO:     192.168.0.186:39440 - "POST /api/agent/gpt4free/command HTTP/1.1" 500 Internal Server Error
agixt_1  | ERROR:    Exception in ASGI application
agixt_1  | Traceback (most recent call last):
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
agixt_1  |     result = await app(  # type: ignore[func-returns-value]
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
agixt_1  |     return await self.app(scope, receive, send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
agixt_1  |     await super().__call__(scope, receive, send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
agixt_1  |     await self.middleware_stack(scope, receive, send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
agixt_1  |     raise exc
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
agixt_1  |     await self.app(scope, receive, _send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
agixt_1  |     await self.app(scope, receive, send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
agixt_1  |     raise exc
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
agixt_1  |     await self.app(scope, receive, sender)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
agixt_1  |     raise e
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
agixt_1  |     await self.app(scope, receive, send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
agixt_1  |     await route.handle(scope, receive, send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
agixt_1  |     await self.app(scope, receive, send)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
agixt_1  |     response = await func(request)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
agixt_1  |     raw_response = await run_endpoint_function(
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
agixt_1  |     return await dependant.call(**values)
agixt_1  |   File "/agixt/endpoints/Extension.py", line 52, in run_command
agixt_1  |     command_output = await Extensions(
agixt_1  |   File "/agixt/Extensions.py", line 195, in execute_command
agixt_1  |     output = await getattr(
agixt_1  |   File "/agixt/extensions/voice_chat.py", line 166, in transcribe_m4a_audio
agixt_1  |     user_input = await self.transcribe_audio_from_file(filename=filename)
agixt_1  |   File "/agixt/extensions/voice_chat.py", line 139, in transcribe_audio_from_file
agixt_1  |     w.transcribe(file_path)
agixt_1  |   File "/usr/local/lib/python3.10/site-packages/whisper_cpp/whisper.py", line 147, in transcribe
agixt_1  |     raise RuntimeError("Failed to read WAV file!")
agixt_1  | RuntimeError: Failed to read WAV file!
```

### Steps to Reproduce the Bug

1.Pass a command through the Typescript SDK or I'm sure it will function the same way through the regular Python for M4A file with base64 string
2. Error will Occur and read it as WAV even though its clearly inputted as M4A

### Expected Behavior

Its suppose to get M4A or specifically the AAC codec from the base64 string from an audio recording.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
The error you're seeing is from Whisper. The `Transcribe M4A Audio` command still converts the M4A to a 16k WAV file for Whisper to transcribe.

https://github.com/Josh-XT/AGiXT/blob/main/agixt/extensions/voice_chat.py
