### ISSUE TITLE
Error During Multistep Task exucution

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1283]
### Description

INFO:     172.18.0.4:56106 - "POST /api/chain/Improving%20Inference%20Speed%20for%20AI%20Models/run HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/agixt/endpoints/Chain.py", line 50, in run_chain
    chain_response = await AGiXT(
  File "/agixt/XT.py", line 599, in execute_chain
    task = await self.run_chain_step(
  File "/agixt/XT.py", line 466, in run_chain_step
    args = self.chain.get_step_content(
  File "/agixt/Chain.py", line 796, in get_step_content
    step_response = self.get_step_response(
  File "/agixt/Chain.py", line 556, in get_step_response
    ChainStep.chain_id == chain_data["id"],
TypeError: list indices must be integers or slices, not str

### Operating System

- [X] Linux
- [ ] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] Python 3.10.X is installed and the version in use on the host machine.
- [X] The latest version of Docker is installed and running on the host machine.
- [X] I am using the latest stable version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by birdup000** [comment]
he error occurs in Chain.py when trying to access chain_data["id"]. The error suggests chain_data is a list but we're trying to access it like a dictionary.
