### ISSUE TITLE
Error on prompt

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1337]
### Description

using the latest branch version v1.6.25 I get this error

```
INFO:     172.18.0.4:38702 - "POST /api/agent/Gemboi/prompt HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/agixt/endpoints/Agent.py", line 340, in prompt_agent
    response = await agent.chat_completions(
  File "/agixt/XT.py", line 1717, in chat_completions
    data_analysis = await self.analyze_data(user_input=new_prompt)
  File "/agixt/XT.py", line 2416, in analyze_data
    return await self.analyze_user_input(user_input=user_input)
  File "/agixt/XT.py", line 2186, in analyze_user_input
    analyze_input = await self.inference(
  File "/agixt/XT.py", line 238, in inference
    response = await self.agent_interactions.run(
  File "/agixt/Interactions.py", line 810, in run
    formatted_prompt, unformatted_prompt, tokens = await self.format_prompt(
  File "/agixt/Interactions.py", line 292, in format_prompt
    conversation_history += c.get_activities_with_subactivities()
  File "/agixt/Conversations.py", line 407, in get_activities_with_subactivities
    current_activity["subactivities"].append(
TypeError: 'NoneType' object is not subscriptable
```

### Operating System

- [X] Linux
- [ ] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] Python 3.10.X is installed and the version in use on the host machine.
- [X] The latest version of Docker is installed and running on the host machine.
- [X] I am using the latest stable version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by Josh-XT** [comment]
Added error handling around empty subactivities and released v1.6.26.
