### ISSUE TITLE
Error in web app - creating/modifying chains

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#665]
### Description

When I try to add a step or modify a step, it throws error

### Steps to Reproduce the Bug

1. Go to Chain Management
2. Modify chain "Task" or other which contains {user_input}
3. Press "Modify step"

Or, create a chain like in the video 
[streamlit-Main-2023-06-11-08-06-26.webm](https://github.com/Josh-XT/AGiXT/assets/5344119/b4b9ca45-5a52-4504-9276-ee696420dc10)

### Expected Behavior

To function without errors

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [ ] Using poetry
- [X] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
Other error:

```
INFO:     127.0.0.1:44986 - "GET /api/agent HTTP/1.1" 200 OK
2023-06-11 08:18:35.955 Uncaught app exception
Traceback (most recent call last):
  File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/mihai/AGiXT/streamlit/pages/3-Interact.py", line 132, in <module>
    learning_page()
  File "/home/mihai/AGiXT/streamlit/components/learning.py", line 8, in learning_page
    agent_name = agent_selector()
  File "/home/mihai/AGiXT/streamlit/components/agent_selector.py", line 27, in agent_selector
    selected_agent = st.selectbox(
  File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 332, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/elements/selectbox.py", line 168, in selectbox
    return self._selectbox(
  File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/elements/selectbox.py", line 227, in _selectbox
    widget_state = register_widget(
  File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/runtime/state/widgets.py", line 163, in register_widget
    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)
  File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/runtime/state/widgets.py", line 208, in register_widget_from_metadata
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.selectbox` widgets with the
same generated key.

When a widget is created, it's assigned an internal key based on
its structure. Multiple widgets with an identical structure will
result in the same internal key, which causes this error.

To fix this error, please pass a unique `key` argument to
`st.selectbox`.
```

**Comment by Josh-XT** [comment]
#670 should have this all sorted out.
