### ISSUE TITLE
Unable to retrieve  data 

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#832]
### Description

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/0c8eb776-88d2-464c-bd10-58094ff71d35)

### Steps to Reproduce the Bug

1.Setup with docker
2.Run Gen and run Task Chain 

### Expected Behavior

No error

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
agixt_1      | INFO:     172.19.0.3:47950 - "GET /api/extensions/settings HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:47954 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:47966 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:47976 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:47984 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:47992 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:47994 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:48008 - "GET /api/provider/custom HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:48010 - "GET /api/extensions HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51068 - "GET /api/agent/easychat/command HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51070 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51088 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51072 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51104 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51114 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51124 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:50432 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:51126 - "GET /api/agent/easychat/command HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:50442 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:50456 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:50470 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:50482 - "GET /api/agent/easychat/command HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:50490 - "PUT /api/agent/easychat/commands HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:50492 - "PUT /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57586 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57588 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57604 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57612 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57622 - "GET /api/agent/easychat/command HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57624 - "PUT /api/agent/easychat/commands HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57626 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:57634 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:43260 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:43276 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:43288 - "GET /api/agent/easychat/command HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:43296 - "PUT /api/agent/easychat/commands HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55086 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55098 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55100 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55116 - "GET /api/agent/easychat HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55128 - "GET /api/agent/easychat/command HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55130 - "GET /api/prompt HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55142 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:55144 - "GET /api/easychat/conversations HTTP/1.1" 200 OK
agixt_1      | []
agixt_1      | INFO:     172.19.0.3:55150 - "GET /api/conversation HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:52848 - "GET /api/prompt HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:52850 - "GET /api/chain HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:52858 - "GET /api/prompt HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:52862 - "GET /api/chain HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:52874 - "GET /api/prompt HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:52890 - "GET /api/chain HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:52894 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:36704 - "GET /api/prompt HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:36710 - "GET /api/chain HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:36724 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:36734 - "GET /api/prompt HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:36736 - "GET /api/chain HTTP/1.1" 200 OK
agixt_1      | INFO:     172.19.0.3:36738 - "GET /api/agent HTTP/1.1" 200 OK
agixt_1      | INFO:     127.0.0.1:59844 - "GET /api/chain/Generate%20and%20Run%20Task%20Chain HTTP/1.1" 200 OK
agixt_1      | 2023-07-09 22:38:09,639 | INFO | Running chain 'Generate and Run Task Chain'
agixt_1      | 2023-07-09 22:38:09,639 | INFO | Running step 1 with agent easychat.
agixt_1      | INFO:     172.19.0.3:36748 - "POST /api/chain/Generate%20and%20Run%20Task%20Chain/run HTTP/1.1" 500 Internal Server Error
agixt_1      | ERROR:    Exception in ASGI application
agixt_1      | Traceback (most recent call last):
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
agixt_1      |     result = await app(  # type: ignore[func-returns-value]
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
agixt_1      |     return await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
agixt_1      |     await super().__call__(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
agixt_1      |     await self.middleware_stack(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
agixt_1      |     raise exc
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
agixt_1      |     await self.app(scope, receive, _send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
agixt_1      |     await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
agixt_1      |     raise exc
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
agixt_1      |     await self.app(scope, receive, sender)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
agixt_1      |     raise e
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
agixt_1      |     await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
agixt_1      |     await route.handle(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
agixt_1      |     await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
agixt_1      |     response = await func(request)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
agixt_1      |     raw_response = await run_endpoint_function(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
agixt_1      |     return await dependant.call(**values)
agixt_1      |   File "/agixt/app.py", line 664, in run_chain
agixt_1      |     chain_response = await Chain().run_chain(
agixt_1      |   File "/agixt/fb/Chain.py", line 338, in run_chain
agixt_1      |     step_response = await self.run_chain_step(
agixt_1      |   File "/agixt/fb/Chain.py", line 293, in run_chain_step
agixt_1      |     chain_name=args["chain_name"],
agixt_1      | KeyError: 'chain_name'

**Comment by greengeckowizard** [comment]
Fixed in b0cf692 Commit
