### ISSUE TITLE
[DOCKER] UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#838]
### Description

```
agixt_1      | INFO:     172.20.0.3:35752 - "POST /api/chain/Generate%20and%20Run%20Smart%20Task%20Chain/run HTTP/1.1" 500 Internal Server Error
agixt_1      | ERROR:    Exception in ASGI application
agixt_1      | Traceback (most recent call last):
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
agixt_1      |     httplib_response = self._make_request(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
agixt_1      |     six.raise_from(e, None)
agixt_1      |   File "<string>", line 3, in raise_from
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 461, in _make_request
agixt_1      |     httplib_response = conn.getresponse()
agixt_1      |   File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
agixt_1      |     response.begin()
agixt_1      |   File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
agixt_1      |     version, status, reason = self._read_status()
agixt_1      |   File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
agixt_1      |     raise RemoteDisconnected("Remote end closed connection without"
agixt_1      | http.client.RemoteDisconnected: Remote end closed connection without response
agixt_1      | 
agixt_1      | During handling of the above exception, another exception occurred:
agixt_1      | 
agixt_1      | Traceback (most recent call last):
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
agixt_1      |     resp = conn.urlopen(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
agixt_1      |     retries = retries.increment(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
agixt_1      |     raise six.reraise(type(error), error, _stacktrace)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
agixt_1      |     raise value.with_traceback(tb)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
agixt_1      |     httplib_response = self._make_request(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
agixt_1      |     six.raise_from(e, None)
agixt_1      |   File "<string>", line 3, in raise_from
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 461, in _make_request
agixt_1      |     httplib_response = conn.getresponse()
agixt_1      |   File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
agixt_1      |     response.begin()
agixt_1      |   File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
agixt_1      |     version, status, reason = self._read_status()
agixt_1      |   File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
agixt_1      |     raise RemoteDisconnected("Remote end closed connection without"
agixt_1      | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
agixt_1      | 
agixt_1      | During handling of the above exception, another exception occurred:
agixt_1      | 
agixt_1      | Traceback (most recent call last):
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/agixtsdk/__init__.py", line 235, in prompt_agent
agixt_1      |     response = requests.post(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
agixt_1      |     return request("post", url, data=data, json=json, **kwargs)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
agixt_1      |     return session.request(method=method, url=url, **kwargs)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
agixt_1      |     resp = self.send(prep, **send_kwargs)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
agixt_1      |     r = adapter.send(request, **kwargs)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
agixt_1      |     raise ConnectionError(err, request=request)
agixt_1      | requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
agixt_1      | 
agixt_1      | During handling of the above exception, another exception occurred:
agixt_1      | 
agixt_1      | Traceback (most recent call last):
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
agixt_1      |     result = await app(  # type: ignore[func-returns-value]
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
agixt_1      |     return await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
agixt_1      |     await super().__call__(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
agixt_1      |     await self.middleware_stack(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
agixt_1      |     raise exc
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
agixt_1      |     await self.app(scope, receive, _send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
agixt_1      |     await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
agixt_1      |     raise exc
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
agixt_1      |     await self.app(scope, receive, sender)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
agixt_1      |     raise e
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
agixt_1      |     await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
agixt_1      |     await route.handle(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
agixt_1      |     await self.app(scope, receive, send)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
agixt_1      |     response = await func(request)
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
agixt_1      |     raw_response = await run_endpoint_function(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
agixt_1      |     return await dependant.call(**values)
agixt_1      |   File "/agixt/app.py", line 663, in run_chain
agixt_1      |     chain_response = await Chain().run_chain(
agixt_1      |   File "/agixt/fb/Chain.py", line 342, in run_chain
agixt_1      |     step_response = await self.run_chain_step(
agixt_1      |   File "/agixt/fb/Chain.py", line 285, in run_chain_step
agixt_1      |     result = ApiClient.prompt_agent(
agixt_1      |   File "/usr/local/lib/python3.10/site-packages/agixtsdk/__init__.py", line 245, in prompt_agent
agixt_1      |     return self.handle_error(response)
agixt_1      | UnboundLocalError: local variable 'response' referenced before assignment
```

### Steps to Reproduce the Bug

1.Run Chain
Error will show after you run it for some time

### Expected Behavior

No error

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
This actually was closed #717 but was never fixed it seems to be the same issue only relating with docker and not local.

**Comment by greengeckowizard** [comment]
This shows sometimes on startup and also during while running chain and can stop the chain and end up messing with the backend afterwards if you try to navigate it won't work since the backend will be messed up.

**Comment by mongolu** [comment]
For me it is happening in all the pages.
For example, in Agent Settings.

Logs:

```
2023-07-11 13:57:57 2023-07-11 10:57:57.292 Uncaught app exception
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 87, in get
2023-07-11 13:57:57     entry_bytes = self._read_from_mem_cache(key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 137, in _read_from_mem_cache
2023-07-11 13:57:57     raise CacheStorageKeyNotFoundError("Key not found in mem cache")
2023-07-11 13:57:57 streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Key not found in mem cache
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_data_api.py", line 634, in read_result
2023-07-11 13:57:57     pickled_entry = self.storage.get(key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 89, in get
2023-07-11 13:57:57     entry_bytes = self._persist_storage.get(key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/local_disk_cache_storage.py", line 155, in get
2023-07-11 13:57:57     raise CacheStorageKeyNotFoundError(
2023-07-11 13:57:57 streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Local disk cache storage is disabled (persist=None)
2023-07-11 13:57:57 
2023-07-11 13:57:57 The above exception was the direct cause of the following exception:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
2023-07-11 13:57:57     cached_result = cache.read_result(value_key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_data_api.py", line 636, in read_result
2023-07-11 13:57:57     raise CacheKeyNotFoundError(str(e)) from e
2023-07-11 13:57:57 streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError: Local disk cache storage is disabled (persist=None)
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 87, in get
2023-07-11 13:57:57     entry_bytes = self._read_from_mem_cache(key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 137, in _read_from_mem_cache
2023-07-11 13:57:57     raise CacheStorageKeyNotFoundError("Key not found in mem cache")
2023-07-11 13:57:57 streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Key not found in mem cache
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_data_api.py", line 634, in read_result
2023-07-11 13:57:57     pickled_entry = self.storage.get(key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/in_memory_cache_storage_wrapper.py", line 89, in get
2023-07-11 13:57:57     entry_bytes = self._persist_storage.get(key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/storage/local_disk_cache_storage.py", line 155, in get
2023-07-11 13:57:57     raise CacheStorageKeyNotFoundError(
2023-07-11 13:57:57 streamlit.runtime.caching.storage.cache_storage_protocol.CacheStorageKeyNotFoundError: Local disk cache storage is disabled (persist=None)
2023-07-11 13:57:57 
2023-07-11 13:57:57 The above exception was the direct cause of the following exception:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss
2023-07-11 13:57:57     cached_result = cache.read_result(value_key)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_data_api.py", line 636, in read_result
2023-07-11 13:57:57     raise CacheKeyNotFoundError(str(e)) from e
2023-07-11 13:57:57 streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError: Local disk cache storage is disabled (persist=None)
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
2023-07-11 13:57:57     conn = connection.create_connection(
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
2023-07-11 13:57:57     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
2023-07-11 13:57:57     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023-07-11 13:57:57 socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
2023-07-11 13:57:57     httplib_response = self._make_request(
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
2023-07-11 13:57:57     conn.request(method, url, **httplib_request_kw)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
2023-07-11 13:57:57     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
2023-07-11 13:57:57     self._send_request(method, url, body, headers, encode_chunked)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
2023-07-11 13:57:57     self.endheaders(body, encode_chunked=encode_chunked)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
2023-07-11 13:57:57     self._send_output(message_body, encode_chunked=encode_chunked)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
2023-07-11 13:57:57     self.send(msg)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/http/client.py", line 976, in send
2023-07-11 13:57:57     self.connect()
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
2023-07-11 13:57:57     conn = self._new_conn()
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
2023-07-11 13:57:57     raise NewConnectionError(
2023-07-11 13:57:57 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f20d1b44940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
2023-07-11 13:57:57     resp = conn.urlopen(
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
2023-07-11 13:57:57     retries = retries.increment(
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
2023-07-11 13:57:57     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2023-07-11 13:57:57 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='agixt', port=7437): Max retries exceeded with url: /api/provider (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20d1b44940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/agixtsdk/__init__.py", line 26, in get_providers
2023-07-11 13:57:57     response = requests.get(
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
2023-07-11 13:57:57     return request("get", url, params=params, **kwargs)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
2023-07-11 13:57:57     return session.request(method=method, url=url, **kwargs)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
2023-07-11 13:57:57     resp = self.send(prep, **send_kwargs)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
2023-07-11 13:57:57     r = adapter.send(request, **kwargs)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
2023-07-11 13:57:57     raise ConnectionError(e, request=request)
2023-07-11 13:57:57 requests.exceptions.ConnectionError: HTTPConnectionPool(host='agixt', port=7437): Max retries exceeded with url: /api/provider (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20d1b44940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-07-11 13:57:57 
2023-07-11 13:57:57 During handling of the above exception, another exception occurred:
2023-07-11 13:57:57 
2023-07-11 13:57:57 Traceback (most recent call last):
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
2023-07-11 13:57:57     exec(code, module.__dict__)
2023-07-11 13:57:57   File "/app/pages/0-Agent_Settings.py", line 46, in <module>
2023-07-11 13:57:57     providers = get_providers()
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
2023-07-11 13:57:57     return cached_func(*args, **kwargs)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
2023-07-11 13:57:57     return self._get_or_create_cached_value(args, kwargs)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
2023-07-11 13:57:57     return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
2023-07-11 13:57:57     computed_value = self._info.func(*func_args, **func_kwargs)
2023-07-11 13:57:57   File "/app/pages/0-Agent_Settings.py", line 18, in get_providers
2023-07-11 13:57:57     return ApiClient.get_providers()
2023-07-11 13:57:57   File "/usr/local/lib/python3.10/site-packages/agixtsdk/__init__.py", line 31, in get_providers
2023-07-11 13:57:57     return self.handle_error(response)
2023-07-11 13:57:57 UnboundLocalError: local variable 'response' referenced before assignment

```

**Comment by Josh-XT** [comment]
Should be fixed now.  Improper tabbing was added in a previous commit.
![image](https://github.com/Josh-XT/AGiXT/assets/102809327/82fd98d6-2660-4205-92a4-35e4debf6dac)

New code also does a return for the user to see when the chain failed now and tells them that they can restart it from whichever step.  It also handles provider errors now, so the "Unable to retrieve data" that you get is your provider failing to respond.  Now if we get that, the chain will stop.

![image](https://github.com/Josh-XT/AGiXT/assets/102809327/66727601-9828-46a4-b3cf-da40470c2138)

![image](https://github.com/Josh-XT/AGiXT/assets/102809327/6bed47c2-5c65-4ba6-91e6-c3ae252d3e35)
