### ISSUE TITLE
ModuleNotFoundError: No module named 'nomic.gpt4all'

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#871]
### Description

I've deleted `agixt-agixt-1` container and the image `joshxt/agixt:latest` and after that did a git pull manually in AGiXT directory (this step don't think it was necessary for continuing with docker).

I've executed `./AGiXT.sh`, chose option 3.

Docker logs for agixt says:
```
2023-08-07 09:31:36 Building wheels for collected packages: nomic
2023-08-07 09:31:36   Building wheel for nomic (setup.py): started
2023-08-07 09:31:36   Building wheel for nomic (setup.py): finished with status 'done'
2023-08-07 09:31:36   Created wheel for nomic: filename=nomic-2.0.5-py3-none-any.whl size=36005 sha256=a1ad6337aa64e1aa0173c90701ca933e45b6f5e504b803a183c5f1cdbbc0648e
2023-08-07 09:31:36   Stored in directory: /root/.cache/pip/wheels/14/12/5e/5f0671353a53dbeac75737abf80d2bfcdd4b2ce12182a53cff
2023-08-07 09:31:36 Successfully built nomic
2023-08-07 09:31:37 Installing collected packages: wonderwords, pygments, pyarrow, mdurl, loguru, jsonlines, fastavro, markdown-it-py, rich, cohere, nomic
2023-08-07 09:31:39 Successfully installed cohere-4.19.2 fastavro-1.8.2 jsonlines-3.1.0 loguru-0.7.0 markdown-it-py-3.0.0 mdurl-0.1.2 nomic-2.0.5 pyarrow-12.0.1 pygments-2.16.1 rich-13.5.2 wonderwords-2.2.0
2023-08-07 09:31:39 Traceback (most recent call last):
2023-08-07 09:31:39   File "/agixt/providers/gpt4all.py", line 5, in <module>
2023-08-07 09:31:39     from nomic.gpt4all import GPT4All
2023-08-07 09:31:39 ModuleNotFoundError: No module named 'nomic'
2023-08-07 09:31:39 
2023-08-07 09:31:39 During handling of the above exception, another exception occurred:
2023-08-07 09:31:39 
2023-08-07 09:31:39 Traceback (most recent call last):
2023-08-07 09:31:39   File "/agixt/Hub.py", line 128, in <module>
2023-08-07 09:31:39     import_agixt_hub()
2023-08-07 09:31:39   File "/agixt/Hub.py", line 121, in import_agixt_hub
2023-08-07 09:31:39     import_providers()
2023-08-07 09:31:39   File "/agixt/db/imports.py", line 350, in import_providers
2023-08-07 09:31:39     provider_options = get_provider_options(provider_name)
2023-08-07 09:31:39   File "/agixt/Providers.py", line 19, in get_provider_options
2023-08-07 09:31:39     module = importlib.import_module(f"providers.{provider_name}")
2023-08-07 09:31:39   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-08-07 09:31:39     return _bootstrap._gcd_import(name[level:], package, level)
2023-08-07 09:31:39   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-08-07 09:31:39   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-08-07 09:31:39   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-08-07 09:31:39   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-08-07 09:31:39   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-08-07 09:31:39   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-08-07 09:31:39   File "/agixt/providers/gpt4all.py", line 8, in <module>
2023-08-07 09:31:39     from nomic.gpt4all import GPT4All
2023-08-07 09:31:39 ModuleNotFoundError: No module named 'nomic.gpt4all'
```

Did a restart for agixt container and now it's ok.
```
2023-08-07 09:46:24 Loading environment variables from .env file in parent directory...
2023-08-07 09:46:24 Waiting for postgres server to start... db:5432
2023-08-07 09:47:02 No changes detected in the AGiXT Hub at AGiXT/hub, moving on...
2023-08-07 09:47:02 Starting AGiXT... Please wait until you see 'Applicaton startup complete' before opening Streamlit...
2023-08-07 09:47:07 INFO:     Uvicorn running on http://0.0.0.0:7437 (Press CTRL+C to quit)
...
```

### Steps to Reproduce the Bug

Described above.

### Expected Behavior

I don't know, it isn't realy a problem.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
I thought it's ok, but it's not.
Because it cracks on import_providers, in web interface I have errors.

**Comment by mongolu** [comment]
I see now it's related with Issue #856

**Comment by mongolu** [comment]
I modified the 2 file with gpt4all in providers to pass, run Hub.py successfully.
Now when i go in the webpage for Agents, make modifications, push the button for update settings, when refresh agents (choose another one and then choose again the modified one), no changes are persisted, all settings are the same as before modifications.
I presume something is not doing what it should on the db side.

**Comment by Josh-XT** [comment]
I just updated the gpt4all.py file in hub to fix this by installing gpt4all as well as nomic.

**Comment by m4t7** [comment]
I assume `nomic.gpt4all import GPT4All` is outdated, I get again the same issue. Has the python binding changed? In the documentation I see only `from gpt4all import GPT4All`
https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-bindings/python/README.md

**Comment by mongolu** [comment]
gpt4all and nomic gets installed, but same error.
