### ISSUE TITLE
Learning does not persist memories to disk (DB_CONNECTED=false)

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#877]
### Description

When I choose Interact / Learning, choose file, wait a bit, message appears `Agent 'Starchat' has learned from file: x`, but no files are in `agents/Starchat/memories`

In console logs is this:
```
agixt-agixt-1                    | INFO:     172.18.0.5:53834 - "GET /api/prompt HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:53848 - "GET /api/agent HTTP/1.1" 200 OK
agixt-agixt-1                    | 2023-08-09 07:23:58,970 | INFO | Successfully imported ClickHouse Connect C data optimizations
agixt-agixt-1                    | 2023-08-09 07:23:58,974 | INFO | Using python library for writing JSON byte strings
agixt-agixt-1                    | 2023-08-09 07:23:59,000 | INFO | No existing DB found in /agixt/agents/Starchat/memories, skipping load
agixt-agixt-1                    | 2023-08-09 07:23:59,001 | INFO | No existing DB found in /agixt/agents/Starchat/memories, skipping load
agixt-agixt-1                    | 2023-08-09 07:24:01,264 | INFO | Load pretrained SentenceTransformer: all-mpnet-base-v2
agixt-agixt-1                    | 2023-08-09 07:24:01,331 | INFO | Created a temporary directory at /tmp/tmpga11fjxl
agixt-agixt-1                    | 2023-08-09 07:24:01,331 | INFO | Writing /tmp/tmpga11fjxl/_remote_module_non_scriptable.py
agixt-agixt-1                    | 2023-08-09 07:24:03,524 | INFO | Generating embeddings for 65153 texts
Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.55it/s]
```

### Steps to Reproduce the Bug

described above

### Expected Behavior

to see some files there (like in other older versions of AGiXT)? 

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
now it says 
`agixt-agixt-1                    | INFO:     172.18.0.5:58374 - "POST /api/agent/Starchat/learn/file HTTP/1.1" 500 Internal Server Error
`

**Comment by mongolu** [comment]
Tried also Interact / Chat , got this

```
agixt-agixt-1                    | INFO:     172.18.0.5:49850 - "GET /api/prompt HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:49852 - "GET /api/agent HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:49856 - "GET /api/Starchat/conversations HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:49868 - "GET /api/conversation HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:49876 - "POST /api/agent/Starchat/prompt HTTP/1.1" 500 Internal Server Error
agixt-agixt-1                    | ERROR:    Exception in ASGI application
agixt-agixt-1                    | Traceback (most recent call last):
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
agixt-agixt-1                    |     result = await app(  # type: ignore[func-returns-value]
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
agixt-agixt-1                    |     return await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
agixt-agixt-1                    |     await super().__call__(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
agixt-agixt-1                    |     await self.middleware_stack(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
agixt-agixt-1                    |     raise exc
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, _send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
agixt-agixt-1                    |     raise exc
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, sender)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
agixt-agixt-1                    |     raise e
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
agixt-agixt-1                    |     await route.handle(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
agixt-agixt-1                    |     await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
agixt-agixt-1                    |     response = await func(request)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
agixt-agixt-1                    |     raw_response = await run_endpoint_function(
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
agixt-agixt-1                    |     return await dependant.call(**values)
agixt-agixt-1                    |   File "/agixt/app.py", line 494, in prompt_agent
agixt-agixt-1                    |     agent = Interactions(agent_name=agent_name)
agixt-agixt-1                    |   File "/agixt/Interactions.py", line 43, in __init__
agixt-agixt-1                    |     self.memories = self.agent.get_memories()
agixt-agixt-1                    |   File "/agixt/fb/Agent.py", line 164, in get_memories
agixt-agixt-1                    |     return Memories(self.agent_name, self.AGENT_CONFIG)
agixt-agixt-1                    |   File "/agixt/Memories.py", line 33, in __init__
agixt-agixt-1                    |     self.chroma_client = ChromaMemoryStore(
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/semantic_kernel/connectors/memory/chroma/chroma_memory_store.py", line 73, in __init__
agixt-agixt-1                    |     self._client = chromadb.Client(self._client_settings)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 81, in Client
agixt-agixt-1                    |     system = System(settings)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/chromadb/config.py", line 175, in __init__
agixt-agixt-1                    |     if settings[key] is not None:
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/chromadb/config.py", line 110, in __getitem__
agixt-agixt-1                    |     raise ValueError(LEGACY_ERROR)
agixt-agixt-1                    | ValueError: You are using a deprecated configuration of Chroma.
agixt-agixt-1                    |
agixt-agixt-1                    | If you do not have data you wish to migrate, you only need to change how you construct
agixt-agixt-1                    | your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
agixt-agixt-1                    | ________________________________________________________________________________________________
agixt-agixt-1                    |
agixt-agixt-1                    | If you do have data you wish to migrate, we have a migration tool you can use in order to
agixt-agixt-1                    | migrate your data to the new Chroma architecture.
agixt-agixt-1                    | Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
agixt-agixt-1                    | change how you construct your Chroma client.
agixt-agixt-1                    |
agixt-agixt-1                    | See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!
agixt-agixt-1                    |
agixt-agixt-1                    | INFO:     172.18.0.5:49892 - "GET /api/prompt HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:49906 - "GET /api/agent HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:49914 - "GET /api/Starchat/conversations HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:49930 - "GET /api/conversation HTTP/1.1" 200 OK

```

**Comment by Josh-XT** [comment]
When v1.3.78 is done building, I think that will fix the issue.  Chroma changed their syntax for making a client with persistence.

**Comment by mongolu** [comment]
Now it says: 
```
2023-08-10 13:06:15   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 36, in <module>
2023-08-10 13:06:15     raise RuntimeError(
2023-08-10 13:06:15 RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
2023-08-10 13:06:15 Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
```

**Comment by mongolu** [comment]
If you `apt install sqlite3`, it installs `sqlite3 (3.34.1-3) ...`

What I've did is more of [this](https://community.render.com/t/your-system-has-an-unsupported-version-of-sqlite3-chroma-requires-sqlite3-3-35-0/13807/4):
```
pip install pysqlite3-binary
cd /usr/local/lib/python3.10/site-packages/chromadb
```
And here replace `__init__.py` line 3 from 
`import sqlite3`
into 
`from pysqlite3 import dbapi2 as sqlite3`

After reloaded the message 
`RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.` didn't appear again.

Now, when Interact / Learning, from url, i get:
```
2023-08-10 14:24:34     // PersistentLocalHnswSegment.get_file_handle_count()
2023-08-10 14:24:34   File "/usr/local/lib/python3.10/site-packages/chromadb/segment/impl/vector/local_persistent_hnsw.py", line 398, in get_file_handle_count
2023-08-10 14:24:34     hnswlib_count = hnswlib.Index.file_handle_count
2023-08-10 14:24:34 AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'
```

If I use instead from file (pdf) i get this one:
```
2023-08-10 14:26:28 INFO:     172.18.0.5:54148 - "GET /api/agent HTTP/1.1" 200 OK
2023-08-10 14:26:29 INFO:     172.18.0.5:54152 - "POST /api/agent/Starchat/learn/file HTTP/1.1" 500 Internal Server Error
```

**Comment by mongolu** [comment]
Teste now (with docker delete container+images), rebuild, v1.3.81
Interact / Learning -> from file has the same error:
`2023-08-10 18:20:15 INFO:     172.18.0.5:43726 - "POST /api/agent/Starchat/learn/file HTTP/1.1" 500 Internal Server Error`

Teste also with url, got: 
```
2023-08-10 18:22:24   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
2023-08-10 18:22:24     return await dependant.call(**values)
2023-08-10 18:22:24   File "/agixt/app.py", line 365, in learn_url
2023-08-10 18:22:24     memories = Agent(agent_name=agent_name).get_memories()
2023-08-10 18:22:24   File "/agixt/fb/Agent.py", line 164, in get_memories
2023-08-10 18:22:24     return Memories(self.agent_name, self.AGENT_CONFIG)
2023-08-10 18:22:24   File "/agixt/Memories.py", line 108, in __init__
2023-08-10 18:22:24     self.embed = Embedding(AGENT_CONFIG=self.agent_config)
2023-08-10 18:22:24   File "/agixt/Embedding.py", line 92, in __init__
2023-08-10 18:22:24     self.embedder, self.chunk_size = get_embedder(
2023-08-10 18:22:24   File "/agixt/Embedding.py", line 33, in get_embedder
2023-08-10 18:22:24     embed = embedding_functions.SentenceTransformerEmbeddingFunction(
2023-08-10 18:22:24 TypeError: SentenceTransformerEmbeddingFunction.__init__() got an unexpected keyword argument 'model_id'
2023-08-10 18:22:24 INFO:     172.18.0.5:44226 - "POST /api/agent/Starchat/learn/url HTTP/1.1" 500 Internal Server Error
```

**Comment by mongolu** [comment]
Went to Agent Settings, Starchat, provider Oobabooga, Embedder "large_local", here it downloaded the embedder model and after this :
```
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
agixt-agixt-1                    |     return await dependant.call(**values)
agixt-agixt-1                    |   File "/agixt/app.py", line 366, in learn_url
agixt-agixt-1                    |     await memories.read_website(url=url.url)
agixt-agixt-1                    |   File "/agixt/Memories.py", line 310, in read_website
agixt-agixt-1                    |     await self.store_result(input=url, result=text_content)
agixt-agixt-1                    |   File "/agixt/Memories.py", line 143, in store_result
agixt-agixt-1                    |     collection.add(
agixt-agixt-1                    | AttributeError: 'coroutine' object has no attribute 'add'
```

**Comment by mongolu** [comment]
hope these tests helps

**Comment by mongolu** [comment]
now it works with Starchat and files and url.
Thing is i've cheked in the agents directory and nothing in Starchat.
Insted, I see

**Comment by Josh-XT** [comment]
I had to do a ton of work to update us to chromadb 0.4.5, but I got it all sorted out today.  It was a bunch of docker work to get it to work.  I would purge your containers entirely and pull fresh, it is much nicer now.

**Comment by mongolu** [comment]
Thank you very much for all the work.

I did that (purge containers, pull fresh), now i see some files and did saw they are growing in dimension while the process of learing was active (i don't know other way to check).
```

root@b938bc1b716c:/agixt# ls -lsa memories/*
284776 -rw-r--r-- 1 root root 291840000 Aug 12 09:40 memories/chroma.sqlite3

memories/b95066f3-920a-468a-9c53-de9d34cc9cc3:
total 52016
    4 drwxr-xr-x 2 root root     4096 Aug 12 08:44 .
    4 drwxr-xr-x 3 root root     4096 Aug 12 09:40 ..
49108 -rw-r--r-- 1 root root 50280000 Aug 12 09:39 data_level0.bin
    4 -rw-r--r-- 1 root root      100 Aug 12 09:39 header.bin
 2520 -rw-r--r-- 1 root root  2578499 Aug 12 09:39 index_metadata.pickle
  124 -rw-r--r-- 1 root root   120000 Aug 12 09:39 length.bin
  252 -rw-r--r-- 1 root root   250900 Aug 12 09:39 link_lists.bin
root@b938bc1b716c:/agixt#
```

**Comment by mongolu** [comment]
I think it can be closed as it is solved. 10x
