### ISSUE TITLE
repo = github_repo.split("/")[1]

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#915]
### Description

When i use Chat with user_input `Analyze this Git Project "https://github.com/joshnh/Git-Commands/".`, it throws this error:

```
agixt-agixt-1                    |     return await dependant.call(**values)
agixt-agixt-1                    |   File "/agixt/app.py", line 536, in prompt_agent
agixt-agixt-1                    |     response = await agent.run(
agixt-agixt-1                    |   File "/agixt/Interactions.py", line 237, in run
agixt-agixt-1                    |     ) = await self.memories.read_website(
agixt-agixt-1                    |   File "/agixt/Memories.py", line 304, in read_website
agixt-agixt-1                    |     await self.read_github_repo(github_repo=url)
agixt-agixt-1                    |   File "/agixt/Memories.py", line 341, in read_github_repo
agixt-agixt-1                    |     repo = github_repo.split("/")[1]
agixt-agixt-1                    | IndexError: list index out of range
```

### Steps to Reproduce the Bug

1. Agent Interactions
2. Select Agent Interaction Mode: Chat
3. Agent Name: Starchat
4. Check "Show Advanced Options" and check all (see picture below)
5. User Input: Analyze this Git Project "https://github.com/joshnh/Git-Commands".

![image](https://github.com/Josh-XT/AGiXT/assets/5344119/cc03ac4c-dfa9-4941-b4c4-0fa5b4fb1796)

Logs:

```
agixt-agixt-1                    | INFO:     172.18.0.5:38438 - "GET /api/Starchat/conversations HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:38444 - "GET /api/conversation HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:38448 - "GET /api/agent HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     127.0.0.1:57154 - "GET /api/agent/Starchat HTTP/1.1" 200 OK
agixt-agixt-1                    |   ***  github_repo = joshnh/Git-Commands".
agixt-agixt-1                    | 2023-08-14 08:03:19,008 | INFO | Browsing link: https://github.com/joshnh/Git-Commands".
agixt-agixt-1                    | 2023-08-14 08:03:22,416 | INFO | Browsing link: https://github.com/joshnh/Git-Commands%22.#start-of-content
agixt-agixt-1                    |   ***  github_repo = joshnh/Git-Commands%22.#start-of-content
agixt-agixt-1                    | 2023-08-14 08:03:25,376 | INFO | Browsing link: https://github.com/
agixt-agixt-1                    |   ***  github_repo =
agixt-agixt-1                    | INFO:     172.18.0.5:38456 - "POST /api/agent/Starchat/prompt HTTP/1.1" 500 Internal Server Error
agixt-agixt-1                    | ERROR:    Exception in ASGI application
agixt-agixt-1                    | Traceback (most recent call last):
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
agixt-agixt-1                    |     result = await app(  # type: ignore[func-returns-value]
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
agixt-agixt-1                    |     return await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
agixt-agixt-1                    |     await super().__call__(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
agixt-agixt-1                    |     await self.middleware_stack(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
agixt-agixt-1                    |     raise exc
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, _send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
agixt-agixt-1                    |     raise exc
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, sender)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
agixt-agixt-1                    |     raise e
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
agixt-agixt-1                    |     await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
agixt-agixt-1                    |     await route.handle(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
agixt-agixt-1                    |     await self.app(scope, receive, send)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
agixt-agixt-1                    |     response = await func(request)
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
agixt-agixt-1                    |     raw_response = await run_endpoint_function(
agixt-agixt-1                    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
agixt-agixt-1                    |     return await dependant.call(**values)
agixt-agixt-1                    |   File "/agixt/app.py", line 536, in prompt_agent
agixt-agixt-1                    |     response = await agent.run(
agixt-agixt-1                    |   File "/agixt/Interactions.py", line 237, in run
agixt-agixt-1                    |     ) = await self.memories.read_website(
agixt-agixt-1                    |   File "/agixt/Memories.py", line 304, in read_website
agixt-agixt-1                    |     await self.read_github_repo(github_repo=url)
agixt-agixt-1                    |   File "/agixt/Memories.py", line 341, in read_github_repo
agixt-agixt-1                    |     repo = github_repo.split("/")[1]
agixt-agixt-1                    | IndexError: list index out of range
agixt-agixt-1                    | INFO:     172.18.0.5:35590 - "GET /api/Starchat/conversations HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:35592 - "GET /api/conversation HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.5:35606 - "GET /api/agent HTTP/1.1" 200 OK
```

### Expected Behavior

to run w/o error

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
Actually, it's bloking, it doesn't continue after the error.

**Comment by mongolu** [comment]
Actually, when "Websearch depth" = 1, it runs past over.

**Comment by Josh-XT** [comment]
This should be resolved now.  I had to rework the function a little bit to accommodate other github urls.

**Comment by Josh-XT** [comment]
Let me know if it is still an issue.  If you're in our discord, feel free to send me a message!  I appreciate your support very much.
