### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by sammcj** [Josh-XT/AGiXT#977]
### Description

Running AGiXT locally with the provided examples and text generation web ui's API gives the following cryptic error:

```
  You can now view your Streamlit app in your browser.

  Network URL: http://<redacted>:8501
  External URL: http://<redacted>:8501


2023-09-13 10:00:33.479 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/0-Agent_Interactions.py", line 37, in <module>
    agent_name = agent_selection() if mode != "Chains" else ""
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:00:39.200 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/1-Agent_Training.py", line 17, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:00:40.134 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:00:45.580 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:00:54.106 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:00:59.237 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/Main.py", line 35, in <module>
    agent_settings = agent_config["settings"]
TypeError: string indices must be integers
2023-09-13 10:01:08.213 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/Main.py", line 35, in <module>
    agent_settings = agent_config["settings"]
TypeError: string indices must be integers
2023-09-13 10:01:17.391 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/0-Agent_Interactions.py", line 37, in <module>
    agent_name = agent_selection() if mode != "Chains" else ""
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:01:21.705 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/0-Agent_Interactions.py", line 37, in <module>
    agent_name = agent_selection() if mode != "Chains" else ""
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:01:26.226 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/0-Agent_Interactions.py", line 37, in <module>
    agent_name = agent_selection() if mode != "Chains" else ""
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:01:28.959 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/1-Agent_Training.py", line 17, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:01:29.555 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:01:31.621 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/3-Memory_Management.py", line 24, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:01:33.156 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/4-Prompt_Management.py", line 44, in <module>
    index=prompt_categories.index("Default"),
ValueError: substring not found
2023-09-13 10:01:57.339 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:03:39.814 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:03:41.915 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
2023-09-13 10:04:26.235 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/3-Memory_Management.py", line 24, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
Error: Expecting value: line 1 column 1 (char 0)
Error: Expecting value: line 1 column 1 (char 0)
Error: Expecting value: line 1 column 1 (char 0)
Error: Expecting value: line 1 column 1 (char 0)
Error: Expecting value: line 1 column 1 (char 0)
Error: Expecting value: line 1 column 1 (char 0)
Error: Expecting value: line 1 column 1 (char 0)
Error: Expecting value: line 1 column 1 (char 0)
```

<img width="1670" alt="image" src="https://github.com/Josh-XT/AGiXT/assets/862951/b77131c1-6455-4c46-890b-00d39b1e44b5">

### Steps to Reproduce the Bug

1. Deploy with docker-compose and text generation web ui's API
2. Access the streamlit web interface
3. Errors occur

### Expected Behavior

No errors, or at least useful errors that tell you what configuration might need to be changed.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [x] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello! Which option in the installer are you running with?

**Comment by sammcj** [comment]
Howdy 👋 , I'm just using the docker images (joshxt/agixt:latest, joshxt/streamlit:latest) with docker compose.

My env configuration looks like:

```env
AGIXT_HUB=${AGIXT_HUB:-AGiXT/hub}
AGIXT_AUTO_UPDATE=true
AGIXT_URI=https://agixt.<redacted>
UVICORN_WORKERS=${UVICORN_WORKERS:-6}
TOKENIZERS_PARALLELISM=false

AI_PROVIDER_URI=https://localai.<redacted>
AI_PROVIDER=oobabooga
PROMPT_PREFIX="USER:"
PROMPT_SUFFIX="\nASSISTANT:"

DB_CONNECTED=true

POSTGRES_SERVER=agixt-db
POSTGRES_DB=agixt
POSTGRES_PORT=5432
POSTGRES_USER=agixt
POSTGRES_PASSWORD=<redacted>
```

**Comment by Josh-XT** [comment]
Try with `DB_CONNECTED=false` - the postgres option may still have some issues to work out.

This block is unnecessary for the ENV file, these items are only referenced by agent config and are not used by env.

```

AI_PROVIDER_URI=https://localai.<redacted>
AI_PROVIDER=oobabooga
PROMPT_PREFIX="USER:"
PROMPT_SUFFIX="\nASSISTANT:"
```

**Comment by sammcj** [comment]
Ah ok thanks, I've disabled the database and commented out that additional block.

The frontend still has error and this in the streamlit container logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/2-Agent_Management.py", line 108, in <module>
    agent_name = agent_selection()
  File "/app/components/selectors.py", line 340, in agent_selection
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
  File "/app/components/selectors.py", line 340, in <listcomp>
    agent_names = [agent["name"] for agent in ApiClient.get_agents()]
TypeError: string indices must be integers
```

and the agixt container is throwing lots of errors with:

```
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
  File "/agixt/Interactions.py", line 8, in <module>
    from readers.website import WebsiteReader
  File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 69, in <module>
    raise RuntimeError(
  File "/agixt/Memories.py", line 6, in <module>
    import chromadb
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
  File "/agixt/app.py", line 11, in <module>
    from Interactions import Interactions, get_tokens
  File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 69, in <module>
    raise RuntimeError(
  File "/agixt/Memories.py", line 6, in <module>
    import chromadb
  File "/agixt/Interactions.py", line 8, in <module>
    from readers.website import WebsiteReader
  File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 69, in <module>
    raise RuntimeError(
  File "/agixt/readers/website.py", line 3, in <module>
    from Memories import Memories
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
  File "/agixt/Memories.py", line 6, in <module>
    import chromadb
  File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 69, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
```

I can see your image has sqlite 3.34.1 which indeed is unsupported by Chroma.

**Comment by Josh-XT** [comment]
Please try using the AGiXT.sh script with option 1. I would recommend first renaming your `.env` file to something else and start with the quick start settings in the install script. You may have some old/strange dependencies there from an old version.

**Comment by sammcj** [comment]
I don't really want to run an installer script on my servers host OS as there's lots of other containers running and everything is deployed in isolation with docker-compose, so I'll close this for now as.

**Comment by Josh-XT** [comment]
I would try another VM. The installer script does a docker-compose pull and sets the environment variables properly. You can open the source of the script and see everything it does.
